# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-10-21 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191013_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('new', 'New'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('paid', 'Paid'), ('shipped', 'Shipped'), ('closed', 'Closed'), ('refunded', 'Refunded')], default='waiting', max_length=20),
        ),
    ]
